version: "3.9"

services:

  configserver:
    build: ./configserver
    container_name: configserver
    ports:
      - "8071:8071"

  eurekaserver:
    build: ./eurekaserver
    container_name: eurekaserver
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
    depends_on:
      - configserver

  accounts:
    build: ./accounts
    container_name: accounts
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    depends_on:
      - configserver
      - eurekaserver

  loans:
    build: ./loans
    container_name: loans
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    depends_on:
      - configserver
      - eurekaserver

  cards:
    build: ./cards
    container_name: cards
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    depends_on:
      - configserver
      - eurekaserver

  gatewayserver:
    build: ./gatewayserver
    container_name: gatewayserver
    ports:
      - "8072:8072"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    depends_on:
      - configserver
      - eurekaserver
