services:

  configserver:
    build:
      context: ./configserver
    container_name: configserver
    ports:
      - "8071:8071"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  eurekaserver:
    build:
      context: ./eurekaserver
    container_name: eurekaserver
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
    depends_on:
      configserver:
        condition: service_healthy

  gatewayserver:
    build:
      context: ./gatewayserver
    container_name: gatewayserver
    ports:
      - "8072:8072"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy

  accounts:
    build:
      context: ./accounts
    container_name: accounts
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy

  loans:
    build:
      context: ./loans
    container_name: loans
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy

  cards:
    build:
      context: ./cards
    container_name: cards
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
